export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    thinkingBorder: string;
    dimSeparator: string;
}

export type Theme = {
    name: string;
    colors: ThemeColors;
}

export const THEMES: Theme[] = [
    {
        name: "Nightfox",
        colors: {
            primary: "#719cd6",
            planMode: "#9d79d6",
            selection: "#223449",
            thinking: "#63cdcf",
            success: "#81b29a",
            error: "#c94f6d",
            info: "#86abdc",
            background: "#192330",
            surface: "#212e3f",
            dialogSurface: "#29394f",
            thinkingBorder: "#394b70",
            dimSeparator: "#575e75",
        },
    },
    {
        name: "Dracula",
        colors: {
            primary: "#bd93f9",
            planMode: "#ff79c6",
            selection: "#44475a",
            thinking: "#8be9fd",
            success: "#50fa7b",
            error: "#ff5555",
            info: "#8be9fd",
            background: "#282a36",
            surface: "#313343",
            dialogSurface: "#383a4a",
            thinkingBorder: "#6272a4",
            dimSeparator: "#6272a4",
        },
    },
    {
        name: "Nord",
        colors: {
            primary: "#88c0d0",
            planMode: "#b48ead",
            selection: "#434c5e",
            thinking: "#8fbcbb",
            success: "#a3be8c",
            error: "#bf616a",
            info: "#81a1c1",
            background: "#2e3440",
            surface: "#3b4252",
            dialogSurface: "#434c5e",
            thinkingBorder: "#4c566a",
            dimSeparator: "#4c566a",
        },
    },
    {
        name: "Gruvbox Dark",
        colors: {
            primary: "#83a598",
            planMode: "#d3869b",
            selection: "#3c3836",
            thinking: "#8ec07c",
            success: "#b8bb26",
            error: "#fb4934",
            info: "#83a598",
            background: "#282828",
            surface: "#32302f",
            dialogSurface: "#3c3836",
            thinkingBorder: "#504945",
            dimSeparator: "#665c54",
        },
    },
    {
        name: "Gruvbox Light",
        colors: {
            primary: "#076678",
            planMode: "#8f3f71",
            selection: "#ebdbb2",
            thinking: "#427b58",
            success: "#79740e",
            error: "#9d0006",
            info: "#076678",
            background: "#fbf1c7",
            surface: "#f2e5bc",
            dialogSurface: "#ebdbb2",
            thinkingBorder: "#d5c4a1",
            dimSeparator: "#bdae93",
        },
    },
    {
        name: "Solarized Dark",
        colors: {
            primary: "#268bd2",
            planMode: "#6c71c4",
            selection: "#073642",
            thinking: "#2aa198",
            success: "#859900",
            error: "#dc322f",
            info: "#268bd2",
            background: "#002b36",
            surface: "#073642",
            dialogSurface: "#0a3c47",
            thinkingBorder: "#586e75",
            dimSeparator: "#586e75",
        },
    },
    {
        name: "Solarized Light",
        colors: {
            primary: "#268bd2",
            planMode: "#6c71c4",
            selection: "#eee8d5",
            thinking: "#2aa198",
            success: "#859900",
            error: "#dc322f",
            info: "#268bd2",
            background: "#fdf6e3",
            surface: "#eee8d5",
            dialogSurface: "#e4ddc9",
            thinkingBorder: "#93a1a1",
            dimSeparator: "#93a1a1",
        },
    },
    {
        name: "Tokyo Night",
        colors: {
            primary: "#7aa2f7",
            planMode: "#bb9af7",
            selection: "#283457",
            thinking: "#7dcfff",
            success: "#9ece6a",
            error: "#f7768e",
            info: "#7aa2f7",
            background: "#1a1b26",
            surface: "#24283b",
            dialogSurface: "#2a2e42",
            thinkingBorder: "#3b4261",
            dimSeparator: "#414868",
        },
    },
    {
        name: "Tokyo Night Storm",
        colors: {
            primary: "#7aa2f7",
            planMode: "#bb9af7",
            selection: "#2d3452",
            thinking: "#7dcfff",
            success: "#9ece6a",
            error: "#f7768e",
            info: "#7aa2f7",
            background: "#24283b",
            surface: "#2f3549",
            dialogSurface: "#363c54",
            thinkingBorder: "#414868",
            dimSeparator: "#565f89",
        },
    },
    {
        name: "Tokyo Night Light",
        colors: {
            primary: "#34548a",
            planMode: "#5a4a78",
            selection: "#c4c8da",
            thinking: "#166775",
            success: "#385f0d",
            error: "#8c4351",
            info: "#34548a",
            background: "#d5d6db",
            surface: "#cbccd1",
            dialogSurface: "#c4c8da",
            thinkingBorder: "#a8aecb",
            dimSeparator: "#9699a3",
        },
    },
    {
        name: "Catppuccin Mocha",
        colors: {
            primary: "#89b4fa",
            planMode: "#cba6f7",
            selection: "#313244",
            thinking: "#94e2d5",
            success: "#a6e3a1",
            error: "#f38ba8",
            info: "#89dceb",
            background: "#1e1e2e",
            surface: "#262637",
            dialogSurface: "#313244",
            thinkingBorder: "#45475a",
            dimSeparator: "#585b70",
        },
    },
    {
        name: "Catppuccin Latte",
        colors: {
            primary: "#1e66f5",
            planMode: "#8839ef",
            selection: "#ccd0da",
            thinking: "#179299",
            success: "#40a02b",
            error: "#d20f39",
            info: "#04a5e5",
            background: "#eff1f5",
            surface: "#e6e9ef",
            dialogSurface: "#ccd0da",
            thinkingBorder: "#bcc0cc",
            dimSeparator: "#acb0be",
        },
    },
    {
        name: "Catppuccin Frappe",
        colors: {
            primary: "#8caaee",
            planMode: "#ca9ee6",
            selection: "#414559",
            thinking: "#81c8be",
            success: "#a6d189",
            error: "#e78284",
            info: "#85c1dc",
            background: "#303446",
            surface: "#383c4d",
            dialogSurface: "#414559",
            thinkingBorder: "#51576d",
            dimSeparator: "#626880",
        },
    },
    {
        name: "Catppuccin Macchiato",
        colors: {
            primary: "#8aadf4",
            planMode: "#c6a0f6",
            selection: "#363a4f",
            thinking: "#8bd5ca",
            success: "#a6da95",
            error: "#ed8796",
            info: "#7dc4e4",
            background: "#24273a",
            surface: "#2c2f42",
            dialogSurface: "#363a4f",
            thinkingBorder: "#494d64",
            dimSeparator: "#5b6078",
        },
    },
    {
        name: "One Dark",
        colors: {
            primary: "#61afef",
            planMode: "#c678dd",
            selection: "#3e4451",
            thinking: "#56b6c2",
            success: "#98c379",
            error: "#e06c75",
            info: "#61afef",
            background: "#282c34",
            surface: "#2f333d",
            dialogSurface: "#353b45",
            thinkingBorder: "#4b5263",
            dimSeparator: "#5c6370",
        },
    },
    {
        name: "One Light",
        colors: {
            primary: "#4078f2",
            planMode: "#a626a4",
            selection: "#e5e5e6",
            thinking: "#0184bc",
            success: "#50a14f",
            error: "#e45649",
            info: "#4078f2",
            background: "#fafafa",
            surface: "#f0f0f1",
            dialogSurface: "#e5e5e6",
            thinkingBorder: "#d3d3d3",
            dimSeparator: "#a0a1a7",
        },
    },
    {
        name: "Monokai",
        colors: {
            primary: "#66d9ef",
            planMode: "#ae81ff",
            selection: "#49483e",
            thinking: "#a1efe4",
            success: "#a6e22e",
            error: "#f92672",
            info: "#66d9ef",
            background: "#272822",
            surface: "#2e2f28",
            dialogSurface: "#3e3d32",
            thinkingBorder: "#75715e",
            dimSeparator: "#75715e",
        },
    },
    {
        name: "Ayu Dark",
        colors: {
            primary: "#39bae6",
            planMode: "#d2a6ff",
            selection: "#253340",
            thinking: "#95e6cb",
            success: "#c2d94c",
            error: "#f07178",
            info: "#59c2ff",
            background: "#0a0e14",
            surface: "#0d1017",
            dialogSurface: "#131721",
            thinkingBorder: "#1b2733",
            dimSeparator: "#3d4149",
        },
    },
    {
        name: "Ayu Mirage",
        colors: {
            primary: "#5ccfe6",
            planMode: "#d4bfff",
            selection: "#33415e",
            thinking: "#95e6cb",
            success: "#bae67e",
            error: "#f28779",
            info: "#73d0ff",
            background: "#1f2430",
            surface: "#232834",
            dialogSurface: "#272d38",
            thinkingBorder: "#343f4c",
            dimSeparator: "#4a5160",
        },
    },
    {
        name: "Ayu Light",
        colors: {
            primary: "#399ee6",
            planMode: "#a37acc",
            selection: "#d1e4f4",
            thinking: "#4cbf99",
            success: "#86b300",
            error: "#f51818",
            info: "#399ee6",
            background: "#fafafa",
            surface: "#f3f4f5",
            dialogSurface: "#e7e8e9",
            thinkingBorder: "#d8d9da",
            dimSeparator: "#828c99",
        },
    },
    {
        name: "Rose Pine",
        colors: {
            primary: "#9ccfd8",
            planMode: "#c4a7e7",
            selection: "#403d52",
            thinking: "#ebbcba",
            success: "#31748f",
            error: "#eb6f92",
            info: "#9ccfd8",
            background: "#191724",
            surface: "#1f1d2e",
            dialogSurface: "#26233a",
            thinkingBorder: "#403d52",
            dimSeparator: "#524f67",
        },
    },
    {
        name: "Rose Pine Moon",
        colors: {
            primary: "#9ccfd8",
            planMode: "#c4a7e7",
            selection: "#44415a",
            thinking: "#ea9a97",
            success: "#3e8fb0",
            error: "#eb6f92",
            info: "#9ccfd8",
            background: "#232136",
            surface: "#2a273f",
            dialogSurface: "#393552",
            thinkingBorder: "#44415a",
            dimSeparator: "#6e6a86",
        },
    },
    {
        name: "Rose Pine Dawn",
        colors: {
            primary: "#286983",
            planMode: "#907aa9",
            selection: "#dfdad9",
            thinking: "#d7827e",
            success: "#56949f",
            error: "#b4637a",
            info: "#286983",
            background: "#faf4ed",
            surface: "#fffaf3",
            dialogSurface: "#f2e9e1",
            thinkingBorder: "#dfdad9",
            dimSeparator: "#9893a5",
        },
    },
    {
        name: "Kanagawa",
        colors: {
            primary: "#7e9cd8",
            planMode: "#957fb8",
            selection: "#2d4f67",
            thinking: "#7aa89f",
            success: "#98bb6c",
            error: "#e82424",
            info: "#7fb4ca",
            background: "#1f1f28",
            surface: "#16161d",
            dialogSurface: "#223249",
            thinkingBorder: "#2a2a37",
            dimSeparator: "#54546d",
        },
    },
    {
        name: "Everforest Dark",
        colors: {
            primary: "#7fbbb3",
            planMode: "#d699b6",
            selection: "#414b50",
            thinking: "#83c092",
            success: "#a7c080",
            error: "#e67e80",
            info: "#7fbbb3",
            background: "#2d353b",
            surface: "#343f44",
            dialogSurface: "#3d484d",
            thinkingBorder: "#475258",
            dimSeparator: "#4f5b58",
        },
    },
    {
        name: "Everforest Light",
        colors: {
            primary: "#3a94c5",
            planMode: "#df69ba",
            selection: "#e0dcc7",
            thinking: "#35a77c",
            success: "#8da101",
            error: "#f85552",
            info: "#3a94c5",
            background: "#fdf6e3",
            surface: "#f4f0d9",
            dialogSurface: "#efebd4",
            thinkingBorder: "#e0dcc7",
            dimSeparator: "#a6b0a0",
        },
    },
    {
        name: "Palenight",
        colors: {
            primary: "#82aaff",
            planMode: "#c792ea",
            selection: "#2f3348",
            thinking: "#89ddff",
            success: "#c3e88d",
            error: "#ff5370",
            info: "#82aaff",
            background: "#292d3e",
            surface: "#1b1e2b",
            dialogSurface: "#34324a",
            thinkingBorder: "#444267",
            dimSeparator: "#676e95",
        },
    },
    {
        name: "Material Ocean",
        colors: {
            primary: "#82aaff",
            planMode: "#c792ea",
            selection: "#1a2332",
            thinking: "#89ddff",
            success: "#c3e88d",
            error: "#ff5370",
            info: "#82aaff",
            background: "#0f111a",
            surface: "#14171f",
            dialogSurface: "#1a1c25",
            thinkingBorder: "#1f2233",
            dimSeparator: "#464b5d",
        },
    },
    {
        name: "Horizon",
        colors: {
            primary: "#26bbd9",
            planMode: "#b877db",
            selection: "#2e2940",
            thinking: "#29d398",
            success: "#29d398",
            error: "#e95678",
            info: "#26bbd9",
            background: "#1c1e26",
            surface: "#232530",
            dialogSurface: "#2e2e40",
            thinkingBorder: "#2e303e",
            dimSeparator: "#6c6f93",
        },
    },
    {
        name: "Synthwave 84",
        colors: {
            primary: "#f92aad",
            planMode: "#b381c5",
            selection: "#34294f",
            thinking: "#36f9f6",
            success: "#72f1b8",
            error: "#fe4450",
            info: "#36f9f6",
            background: "#2a2139",
            surface: "#241b2f",
            dialogSurface: "#34294f",
            thinkingBorder: "#495495",
            dimSeparator: "#495495",
        },
    },
    {
        name: "Cobalt2",
        colors: {
            primary: "#0088ff",
            planMode: "#ff9d00",
            selection: "#003f8e",
            thinking: "#80fcff",
            success: "#3ad900",
            error: "#ff2222",
            info: "#0088ff",
            background: "#193549",
            surface: "#15232d",
            dialogSurface: "#1f4662",
            thinkingBorder: "#0d3a58",
            dimSeparator: "#1f4662",
        },
    },
    {
        name: "Night Owl",
        colors: {
            primary: "#82aaff",
            planMode: "#c792ea",
            selection: "#1d3b53",
            thinking: "#7fdbca",
            success: "#addb67",
            error: "#ef5350",
            info: "#82aaff",
            background: "#011627",
            surface: "#0b2942",
            dialogSurface: "#122d42",
            thinkingBorder: "#1d3b53",
            dimSeparator: "#5f7e97",
        },
    },
    {
        name: "Github Dark",
        colors: {
            primary: "#58a6ff",
            planMode: "#bc8cff",
            selection: "#264f78",
            thinking: "#39c5cf",
            success: "#3fb950",
            error: "#f85149",
            info: "#58a6ff",
            background: "#0d1117",
            surface: "#161b22",
            dialogSurface: "#1c2128",
            thinkingBorder: "#30363d",
            dimSeparator: "#21262d",
        },
    },
    {
        name: "Github Light",
        colors: {
            primary: "#0969da",
            planMode: "#8250df",
            selection: "#ddf4ff",
            thinking: "#1b7c83",
            success: "#1a7f37",
            error: "#cf222e",
            info: "#0969da",
            background: "#ffffff",
            surface: "#f6f8fa",
            dialogSurface: "#eaeef2",
            thinkingBorder: "#d0d7de",
            dimSeparator: "#d8dee4",
        },
    },
    {
        name: "Zenburn",
        colors: {
            primary: "#8cd0d3",
            planMode: "#dc8cc3",
            selection: "#4f4f4f",
            thinking: "#93e0e3",
            success: "#9fce9f",
            error: "#cc9393",
            info: "#8cd0d3",
            background: "#3f3f3f",
            surface: "#4a4a4a",
            dialogSurface: "#545454",
            thinkingBorder: "#5f5f5f",
            dimSeparator: "#6f6f6f",
        },
    },
];

export const DEFAULT_THEME = THEMES.find((t)=>t.name==="Nightfox")!